version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    open-pull-requests-limit: 10000 # HACK: Set this to a stupid high number so we continue getting PRs as there appears to be a bug with Dependabot ğŸ¤·â€â™‚ï¸ https://github.com/dependabot/dependabot-core/issues/12224
    schedule:
      interval: "daily"
    reviewers:
      - lithiumtoast
    target-branch: main
